### ISSUE TITLE
handlebars not accepted in yaml

### ISSUE THREAD

**Issue by Morriz** [sivasamyk/logtrail#321]
Hi, as most of us use this in a Configmap, the handlebars notation in the json is giving helm errors:

`unexpected "{" in command`

relevant part:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    app: kibana
data:
  logtrail.json: |
    {
      "index_patterns" : [
        {
          "es": {
            "default_index": "kube-system-*"
          },
...
            "message_format": "[{{{object.source.host}}}::{{{object.involvedObject.name}}}] {{{object.type}}} - {{{object.involvedObject.name}}} : {{{message}}}",
            "keyword_suffix" : ""
```

**Comment by sivasamyk** [comment]
Can you try reading the logtrail.json from file like below?
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    app: kibana
data:
  {{ (.Files.Glob "files/logtrail.json").AsConfig }}
```

where <chart-loc>/files/logtrail.json contains the actual config.
